version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: ${COMPOSE_PROJECT_NAME}.mongodb.docker
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_NAME}
    volumes:
      - mongodb-data:/data/db
    ports:
      - ${MONGO_PORT}:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=12345   
  
  frontend: 
    image: frontend
    ports: 
      - 4000:4000

volumes:
  mongodb-data:
    driver: local
        

